# 存储配置
store:
  engine: pebble
  path: ./db/1/

# server 相关
server:
  # grpc 配置
  grpc_port: 9000
  # http 配置
  http_port: 8081
  # 限流容量，每秒的 qps 限制
  rate: 1000
  # 慢请求的阈值，单位为 ms
  slow_query_threshold: 100

# 集群相关
cluster:
  # node_id，不能重复，得唯一
  node_id: 1
  # raft 协议提交的日志存储位置
  path: ./cluster/
  # 通信的端口
  port: 9090
  # 提交超时时间，单位为 ms
  time_out: 1000